version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      time: '04:00'
    groups:
      dependencies:
        exclude-patterns:
          - "types-*"
        update-types:
          - "minor"
          - "patch"
      types:
        patterns:
          - "types-*"
