language: python
dist: xenial
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -b -p "*.py" test_dbupgrade
  - mypy dbupgrade test_dbupgrade
  - flake8 dbupgrade test_dbupgrade
