language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -b -p "*.py" test_dbupgrade
  - mypy dbupgrade test_dbupgrade
  - flake8 dbupgrade test_dbupgrade
