name: Test and lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 --version
        flake8 --show-source --statistics dbupgrade test_dbupgrade
    - name: Type checking with mypy
      run: |
        mypy --version
        mypy dbupgrade test_dbupgrade
    - name: Test with unittest
      run: python -m unittest discover -b -p "*.py" test_dbupgrade
